---
title: "PM566 Final Project"
author: "Changqing Su"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my PM566 Final Project website.

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}

library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = F,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```

# Lab 12


```{r, warning=FALSE,message=FALSE,echo = FALSE}
source("process_COVID_DATA.R")
```


```{r plot1, class.source="code-r-small"}
p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")
p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
```





## Showcasing plots {.tabset}

### Figure 1

```{r p1, echo=FALSE}
p1_scatter
```

### Figure 2

```{r p2, echo=FALSE}
p2_scatter
```

## {-}



# Assignment 5 

```{r, warning=FALSE,message=FALSE,echo = FALSE}
source("Mid_data.R")
```

```{r midtermplots, class.source="code-r-small"}

figure1=covid_2  %>%
plot_ly(x = ~`Age group`, y = ~PMR, 
        type = 'scatter', mode = 'markers', color = ~State,
        size = ~`Total Deaths`, sizes = c(2, 30), 
         marker = list(sizemode='diameter', opacity=0.6)) %>%
  layout(title = "Age groups vs PMR by states",
                  yaxis = list(title = "Proportionate Mortality Ratio"), xaxis = list(title = "Age groups"))
  

figure2= covid_2 %>%
  plot_ly(x=~State , y = ~`COVID-19 Deaths`, color = ~Sex) %>%
  layout(title = "State vs COVID-19 Deaths by Sex",
                  yaxis = list(title = "COVID-19 Deaths"), xaxis = list(title = "State"))
  

figure3 =covid_2 %>%
  plot_ly(x=~`Age group` , y = ~PMR, color = ~Sex) %>%
  add_bars() %>%
  layout(title = "Age group vs PMR by Sex",
                  yaxis = list(title = "Proportionate Mortality Ratio"), xaxis = list(title = "Age group "),barmode = "stack") 





g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  lakecolor = toRGB('white')
)

figure4=plot_geo(covid_state) %>%
  add_trace(
    z = ~PMR, text = ~State, span = I(0),
    locations = state.abb, locationmode = 'USA-states' , color="Reds") %>% 
  layout(title='Covid PMR Map',
         geo = g)


```

## Midterm project plots {.tabset}

### Figure 1

```{r PMR within different age groups by states, echo=FALSE}
figure1
```

### Figure 2

```{r Covid deaths within different sex by states, echo=FALSE}
figure2
```

### Figure 3

```{r PMR within different sex by age groups, echo=FALSE}
figure3
```

### Figure 4

```{r PMR Map, echo=FALSE}
figure4
```



